YES=Y
NO=N

defaultlabelformat={0}
defaultlabelformat.tivoli09={0}:
defaultlabelformat.tivoli13={0}:
defaultlabelformat.iot18={0}:
tablecolYORNlabelformat={0}?
titlesepformat={0}:
isDoubleByte=false
filtertitlespace=true

HOTKEY_ALT=ALT
HOTKEY_CTRL=CTRL